name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
      with:
          path: 'source'
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Create Dockerfile
      run: |
          echo "Current directory: $(pwd)"
          echo "Creating Dockerfile at: ${{ github.workspace }}/Dockerfile"
          cat <<EOF > "${{ github.workspace }}/Dockerfile"
          FROM python:3.12-slim
          WORKDIR /app
          COPY . .
          RUN pip install --no-cache-dir -r requirements.txt
          CMD ["python", "main.py"]
          EOF
          echo "Dockerfile content:"
          cat "${{ github.workspace }}/Dockerfile"
          echo "Directory contents:"
          ls -la "${{ github.workspace }}"

      # Шаг 2: Сборка с абсолютными путями
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max