name: Build and Delivery

on:
  workflow_run:
    workflows: ["Test Python App"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'source'  # Явно указываем путь для checkout

      - name: Create Dockerfile
        working-directory: ${{ github.workspace }}/source
        run: |
          cat <<EOF > Dockerfile
          FROM python:3.12-slim
          WORKDIR /app
          COPY . .
          RUN pip install --no-cache-dir -r requirements.txt
          CMD ["python", "main.py"]
          EOF
          echo "Dockerfile content:"
          cat Dockerfile
          echo "Directory contents:"
          ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/source  # Используем локальный контекст
          file: ${{ github.workspace }}/source/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
          no-cache: true  # Отключаем кэш для чистого билда